name: CI

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - javascript/**
  pull_request:
    branches: [ '*' ]
    paths:
      - javascript/**

jobs:
  linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.5]

    steps:
    - uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: npm install
      working-directory: ./javascript
      run: npm install

    - name: pass linters
      working-directory: ./javascript
      run: npm run lint

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.5]

    steps:
    - uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: npm install
      working-directory: ./javascript
      run: npm install

    - name: pass unit test
      working-directory: ./javascript
      run: npm run test

  e2e-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.15.5]

    steps:
    - uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: npm install
      working-directory: ./javascript
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        install: false
        command: npm run e2e
        working-directory: ./javascript/

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: javascript/dist/cypress/apps/taiga-e2e/screenshots

    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: javascript/dist/cypress/apps/taiga-e2e/videos
