name: CI front

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - javascript/**
  pull_request:
    branches: [ '*' ]
    paths:
      - javascript/**

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ./javascript
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

  linters:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: pass linters
      working-directory: ./javascript
      run: npm run lint

  unit-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: pass unit test
      working-directory: ./javascript
      run: npm run test

  e2e-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        install: false
        command: npm run e2e
        working-directory: ./javascript/

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: javascript/dist/cypress/apps/taiga-e2e/screenshots

    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: javascript/dist/cypress/apps/taiga-e2e/videos
