name: CI front

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - javascript/**
  pull_request:
    branches: [ '*' ]
    paths:
      - javascript/**

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install front
    - name: Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ./javascript
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

  linters:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: pass linters
      working-directory: ./javascript
      run: npm run lint

  unit-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json

    - name: cache npm ci
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ./javascript/node_modules
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('./javascript/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: pass unit test
      working-directory: ./javascript
      run: npm run test
